/*import type { NextPage } from 'next'
import Head from 'next/head'
import {Box} from "@chakra-ui/react";
import NavigationBar from "../layouts/NavigationBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar>
        <Box>Contenuto</Box>
      </NavigationBar>
    </>
  )
}

export default Home*/

import { useState, useEffect } from 'react'
import { supabase } from '../lib/SupabaseClient';
import { Session } from "@supabase/supabase-js";
import Auth from '../components/Auth'
import Account from '../components/Account'
import {Button, useColorMode} from "@chakra-ui/react";

export default function Home() {
  const [session, setSession] = useState<Session | null>(null);
  const { colorMode, toggleColorMode } = useColorMode()

  useEffect(() => {
    setSession(supabase.auth.session())

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

  return (
    <>
      <header>
        <Button onClick={toggleColorMode}>
          Toggle {colorMode === 'light' ? 'Dark' : 'Light'}
        </Button>
      </header>
      <div className="container" style={{ padding: '50px 0 100px 0' }}>
        {!session ? <Auth /> : <Account key={session?.user?.id} session={session} />}
      </div>
    </>
  )
}
