import type { NextPage } from 'next'
import Head from 'next/head'
import {Box} from "@chakra-ui/react";
import NavigationBar from "../layouts/NavigationBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar>
        <Box>Contenuto</Box>
      </NavigationBar>
    </>
  )
}

export default Home
